"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "change-me-in-production",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'rest_framework',
    'corsheaders',
    'gunicorn',
    'parler',
    'django_filters',
    'drf_spectacular',
    'safedelete',
    'storages',
    'requests',

    'apps.rag',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	"corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

APPEND_SLASH=True

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://:{os.getenv("REDIS_PASSWORD")}@{os.getenv("REDIS_HOST", "host.docker.internal")}:{os.getenv("REDIS_PORT", 6379)}/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
        },
        'KEY_PREFIX': '',
        'VERSION': '',
        'KEY_FUNCTION': 'config.helpers.get_cache_key',
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=60),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'config.authentication.CustomBearerAuthentication',
    ],
    # 'DEFAULT_PAGINATION_CLASS': 'config.pagination.PageNumberPagination',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'config.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('THROTTLE_ANON', '30/minute'),
        'user': os.getenv('THROTTLE_USER', '120/minute'),
    },
}

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    origin for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if origin
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://127.0.0.1',
]


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if os.getenv('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ru"

LANGUAGES = [
    ('uz-lat', 'Uzbek (Latin)'),  # uz-Latin
    ('uz-crl', 'Uzbek (Cyrillic)'),  # uz-Cyrillic
    ('ru', 'Russian'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'lang'),
]

PARLER_LANGUAGES = {
    None: (
        {'code': 'uz-lat', 'fallbacks': ['ru', 'en']},
        {'code': 'uz-crl', 'fallbacks': ['ru', 'en']},
        {'code': 'ru', 'fallbacks': ['en']},
        {'code': 'en'},
    ),
    'default': {
        'fallback': 'uz-crl',
        'hide_untranslated': False,
    },
}

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

DOMAIN_URL = os.getenv("DOMAIN_URL", "localhost:8000")

STATIC_URL = os.getenv('STATIC_URL', '/static/')
STATIC_ROOT = os.getenv('STATIC_ROOT', str(BASE_DIR / 'static'))
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = os.getenv('MEDIA_ROOT', str(BASE_DIR / 'media'))


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'app.log'),
            'maxBytes': 1024*1024*5,  # 5 MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    # 'loggers': {
    #     'django.db.backends': {
    #         'level': 'DEBUG',
    #         'handlers': ['file'],
    #     },
    # },
}


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CELERY setting
CELERY_TIMEZONE = "Asia/Tashkent"
CELERY_TASK_TRACK_STARTED = True
CELERY_BROKER_URL = f'redis://:{os.getenv("REDIS_PASSWORD")}@{os.getenv("REDIS_HOST", "host.docker.internal")}:{os.getenv("REDIS_PORT", 6379)}/5'
CELERY_RESULT_BACKEND = f'redis://:{os.getenv("REDIS_PASSWORD")}@{os.getenv("REDIS_HOST", "host.docker.internal")}:{os.getenv("REDIS_PORT", 6379)}/5'
CELERY_TASK_DEFAULT_RETRY_DELAY = 5  # seconds
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_STORE_ERRORS_EVEN_IF_IGNORED = True
CELERY_TASK_IGNORE_RESULT = False
CELERY_RESULT_EXPIRES = 432000
CELERY_REDIS_BACKEND_SETTINGS = {
    'keyprefix': 'do_utg_queue_celery'
}

# RAG settings
RAG_ENABLED = os.getenv('RAG_ENABLED', 'True') == 'True'
RAG_DEFAULT_TENANT_ID = os.getenv('RAG_DEFAULT_TENANT_ID', 'default')
RAG_VECTOR_COLLECTION_PREFIX = os.getenv('RAG_VECTOR_COLLECTION_PREFIX', 'rag')

RAG_QDRANT_URL = os.getenv('RAG_QDRANT_URL', '')
RAG_QDRANT_API_KEY = os.getenv('RAG_QDRANT_API_KEY', '')

RAG_LLM_API_KEY = os.getenv('RAG_LLM_API_KEY', 'unused')
RAG_LLM_BASE_URL = os.getenv('RAG_LLM_BASE_URL', os.getenv('RAG_LLM_ENDPOINT', 'http://localhost:12434/engines/llama.cpp/v1'))
RAG_LLM_MODEL = os.getenv('RAG_LLM_MODEL', 'ai/qwen3:4b')
RAG_LLM_TEMPERATURE = float(os.getenv('RAG_LLM_TEMPERATURE', '0.2'))
RAG_LLM_MAX_TOKENS = int(os.getenv('RAG_LLM_MAX_TOKENS', '1024'))

RAG_EMBEDDING_BASE_URL = os.getenv('RAG_EMBEDDING_BASE_URL', os.getenv('RAG_EMBEDDING_ENDPOINT', 'http://localhost:12434/engines/llama.cpp/v1'))
RAG_EMBEDDING_MODEL = os.getenv('RAG_EMBEDDING_MODEL', 'ai/baai/bge-small-en-v1.5')
RAG_EMBEDDING_MODEL_VERSION = os.getenv('RAG_EMBEDDING_MODEL_VERSION', 'latest')

RAG_CHUNK_SIZE = int(os.getenv('RAG_CHUNK_SIZE', '900'))
RAG_CHUNK_OVERLAP = int(os.getenv('RAG_CHUNK_OVERLAP', '180'))

RAG_TOP_K = int(os.getenv('RAG_TOP_K', '5'))
RAG_MAX_TOP_K = int(os.getenv('RAG_MAX_TOP_K', '20'))
RAG_MODEL_TIMEOUT_SECONDS = int(os.getenv('RAG_MODEL_TIMEOUT_SECONDS', '60'))

RAG_REEMBED_ON_VERSION_MISMATCH = os.getenv('RAG_REEMBED_ON_VERSION_MISMATCH', 'True') == 'True'
RAG_REEMBED_BATCH_SIZE = int(os.getenv('RAG_REEMBED_BATCH_SIZE', '64'))