[supervisord]
logfile=/app/src/logs/supervisord.log
nodaemon=true

[program:gunicorn]
command=gunicorn config.wsgi:application --config ./docker/gunicorn/gunicorn.conf.py --reload --workers 1
directory=/app/src
autostart=true
autorestart=true
stdout_logfile=/app/src/logs/gunicorn.log
stderr_logfile=/app/src/logs/gunicorn_error.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=DJANGO_SETTINGS_MODULE=config.settings

[program:flower_celery_task_monitoring]
command=celery -A config flower --basic-auth=%(ENV_FLOWER_BASIC_AUTH)s --port=5555
directory=/app/src
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/src/logs/flower_celery_task_monitoring.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1

[program:celery_task_worker]
command=celery -A config worker -E --loglevel=warning --concurrency=2 -n worker%(process_num)s@%%h
process_name=%(program_name)s_%(process_num)02d
directory=/app/src
numprocs=4
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/src/logs/celery_task_worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

# [program:send_notification]
# command=python manage.py send_notification
# autostart=true
# autorestart=true
# redirect_stderr=true
# numprocs=1
# startsecs=0
# startretries=3
# exitcodes=0
# stopsignal=QUIT
# stopwaitsecs=60
# stdout_logfile=/app/logs/send_notification.log
# stdout_logfile_maxbytes=10MB
# stdout_logfile_backups=5